quora7/accounts/urls.py
from django.urls import path
from accounts import views

app_name="accounts"

urlpatterns = [
    path('login/',views.login_page,name='login'),
    path('logout/',views.logout_page,name='logout'),
    path('register/',views.register,name='register'),

    ]

quora7/quora3/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("quorapp.urls")),
    path('', include("accounts.urls")),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

quora7/quorapp/urls.py
from django.urls import path
from quorapp import views

app_name = "quorapp"

urlpatterns = [
    path('', views.index, name='index'),
    path('base/', views.base, name='base'),
    path('addquestion/', views.addquestion, name='addquestion'),
    path('detail/<slug:slug>/', views.detail, name='detail'),
    path('like/<int:id>/', views.like_question, name='like'),
    path('dislike/<int:id>/', views.dislike_question, name='dislike'),
]

quora7/accounts/models.py
from django.db import models

# Create your models here.

quora7/quorapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify


# Create your models here.
class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    body = models.TextField()
    image = models.ImageField(upload_to='ques-image/', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    likes = models.IntegerField(default=0)
    dislikes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title



class Answers(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    question = models.ForeignKey(Question, null=False, on_delete=models.CASCADE, related_name='answers')
    body = models.TextField()
    slug = models.SlugField(unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.body



quora7/quorapp/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import Question,Answers

class userform(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']

class Answers_form(forms.ModelForm):
  class Meta:
    model = Answers
    fields =['body','slug']

class Question_form(forms.ModelForm):
    class Meta:
        model=Question
        fields = ['title','body','image', 'slug']
      

quora7/accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login,logout  
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


# Create your views here.
def login_page(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # log the user in
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
               return redirect('quorapp:index')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', { 'form': form })


def register(request):
    if request.method == 'POST':
         form = UserCreationForm(request.POST)
         if form.is_valid():
             user = form.save()
             #  log the user in
             login(request, user)
             return redirect('quorapp:index')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/register.html', { 'form': form })


def logout_page(request):
    logout(request)
    return redirect("quorapp:index")

quora7/quorapp/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from .forms import Answers_form,Question_form
from .models import Question,Answers
from django.contrib.auth.forms import UserCreationForm

# Create your views here.


def index(request):
    all_questions = Question.objects.all().order_by('-created_at')
    return render(request, 'index.html', { 'all_questions': all_questions })

def base(request):
    return render(request,'base.html')

@login_required(login_url="/login/")
def addquestion(request):
    form = Question_form()
    if request.method == 'POST':
        form = Question_form(request.POST, request.FILES)
        if form.is_valid():
            question = form.save(commit=False)  # Create the question instance but don't save it yet
            question.author = request.user  # Assign the current logged-in user as the author
            question.save()  # Save the question with the author assigned
            return redirect('quorapp:index')
    else:
        all_questions = Question.objects.all().order_by('created_at')
        return render(request, 'addquestion.html', {'form': form, 'all_questions': all_questions})



@login_required(login_url="/login/")
def display_questions(request):
    all_questions = Question.objects.all().order_by('created_at')
    return render(request, 'index.html', {'all_questions': all_questions})

@login_required(login_url="/login/")
def detail(request, slug):
    question = Question.objects.get(slug=slug)
    answers = Answers.objects.filter(question=question).order_by('-updated_at')
    answer_form = Answers_form()

    if request.method == 'POST':
        answer_data = Answers_form(request.POST)
        if answer_data.is_valid():
            answer = answer_data.save(commit=False)
            answer.question = question
            answer.user = request.user
            answer.save()
            return redirect('quorapp:detail', slug=slug)

    return render(request, 'detail.html', {
        'question': question,
        'answers': answers,
        'answer_form': answer_form,
    })

@login_required(login_url="/login/")
def like_question(request, id):
    question = Question.objects.get(pk=id)
    question.likes += 1
    question.save()

    return redirect('quorapp:index')

@login_required(login_url="/login/")
def dislike_question(request, id):
    question = Question.objects.get(pk=id)
    question.dislikes += 1
    question.save()

    return redirect('quorapp:index')

quora7/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}

    <div class="container m-3 ">
        <h1>Log in</h1>
        <form class="site-form mb-1" action="{% url 'accounts:login' %}" method="post">
          {% csrf_token %}
          {{ form.as_p }}
          {% if request.GET.next %}
              <input type="hidden" name="next" value="{{ request.GET.next }}" />
          {% endif %}
          <input type="submit" value="Login" />
        </form>
        <p>Not got an account? <a href="{% url 'accounts:register' %}">Register</a></p>
  </div>
{% endblock %}

quora7/accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block content %}
<div class="container ">
    <h1>Register</h1>
    <form class="site-form mt-4" action="{% url 'accounts:register' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Register" class="btn btn-primary mt-0">
    </form>
</div>
{% endblock %}

quora7/templates/addquestion.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="jumbotron">
            <h2 class=" text-center">Create a New questions</h2>
            <form class="col-6 mx-auto card p-3 shadow-lg" action="{% url 'quorapp:addquestion' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Submit</button>
                <p class="text-center">Want to go back to Main page? <a href="{% url 'quorapp:index' %}">Click here</a></p>
            </form>
        </div>
    </div>
{% endblock %}

quora7/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{page}}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <style>
        table, th, td {
          border:1px solid black;
        }
    </style>
</head>
<body>
    <nav class="navbar bg-warning p-3 shadow-lg">
        <div class="container-fluid">
            <div class="d-flex">
                <a class="navbar-brand"> <strong>QUORA</strong></a>
                <a href="{% url 'quorapp:index' %}" class="navbar-brand">Home</a>
            </div>
            <form class="d-flex" role="search">
                <a href="{% url 'quorapp:addquestion' %}" class="btn btn-danger me-2">Add Question</a>
                {% if request.user.is_authenticated %}
                    <a href="{% url 'accounts:logout' %}" class="btn btn-success" type="submit">Logut</a>
                {% else %}
                    <a href="{% url 'accounts:login' %}" class="btn btn-success" type="submit">Login</a>
                {% endif %}
            </form>
        </div>
      </nav>
</body>
</html>
{% block content %}

{% endblock %}

<script>
    console.log("heyy hiii django")
</script>

quora7/templates/detail.html
<!-- detail.html -->
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="card mt-4 ">
            <div class="d-inline p-3 fs-3">
            <p> Question title - <em>{{ question.title }}</em></p>
                
            <p>Question is - <strong> {{ question.body }}</strong> </p>
            </div>
        </div>

        <div class="card mt-4">
            <div class="card-body">
                <h4 class="card-title">Answer the Question</h4>
                <form method="POST" action="{% url 'quorapp:detail' slug=question.slug %}">
                    {% csrf_token %}
                    {{ answer_form.as_p }}
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>

        <div class="card mt-4">
            <div class="card-body">
                <h4 class="card-title">Answers</h4>
                {% for answer in answers %}
                    <div class="card mt-3">
                        <div class="card-body">
                            <h5 class="card-title">{{ answer.user.username }}</h5>
                            <p class="card-text">{{ answer.body }}</p>
                            <p class="card-text"><small class="text-muted">Updated at: {{ answer.updated_at }}</small></p>
                        </div>
                    </div>
                {% empty %}
                    <p>No answers yet.</p>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

quora7/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<h1 class="text-center m-5">Welcome!! Know the answer to all Questions</h1>

<div class="articles container jumbotron">

    {% for question in all_questions %}
        <div class="col-6 card mx-auto p-3 shadow-lg mb-3">
            <h2> User -> {{ question.author.username }}</h2>
            <h2>Question Title -> <strong>{{ question.title }}</strong></h2>
            <h3>Question -> {{ question.body }}</h3>
            <h5>Posted at -> {{ question.created_at }}</h5>
            {% if question.image %}
                <img src="{{ question.image.url }}" style="height: 400px; width: auto;" />
            {% endif %}

            <a href="{% url 'quorapp:detail' slug=question.slug %}">See and Write Answers</a>

            
           
            <div class="d-flex align-items-center mt-3">
                <p class="m-0 me-5 mb-3">Likes: {{ question.likes }}</p>
                <form action="{% url 'quorapp:like' question.id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary btn-sm">Like</button>
                </form>
            </div>

            
            <div class="d-flex align-items-center">
                <p class="m-0 me-4">Dislikes: {{ question.dislikes }}</p>
                <form action="{% url 'quorapp:dislike' question.id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger btn-sm">Dislike</button>
                </form>
            </div>
            
        </div>
    {% endfor %}
</div>

{% endblock %}